/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package ale.portScandroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int from=0x7f050008;
        public static final int from_label=0x7f050007;
        public static final int host_label=0x7f050001;
        public static final int hostname=0x7f050002;
        public static final int result=0x7f05000a;
        public static final int scan=0x7f050005;
        public static final int to=0x7f050004;
        public static final int to_label=0x7f050003;
        public static final int udp=0x7f050006;
        public static final int widget30=0x7f050000;
        public static final int widget41=0x7f050009;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
